FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1
WORKDIR /app

# Instala curl e atualiza pacotes
RUN apt-get update && apt-get install -y curl

COPY requirements.txt requirements.txt

# Atualiza o pip
RUN python -m pip install --upgrade pip

# Instala as dependências
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV FLASK_APP=app.py

EXPOSE 5000

CMD ["flask", "run", "--host=0.0.0.0", "--port=5000", "--debug"]
